# Generated by Django 5.0.6 on 2024-07-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='reg',
        ),
    ]
